import { useEffect, useState } from "react";
import Navbar from "./Navbar";

const apiUrl = import.meta.env.VITE_API_URL || "";

export default function StoryPage() {
  const [contact, setContact] = useState(null);
  useEffect(() => { fetch(`${apiUrl}/api/settings/contact`).then((response) => response.ok ? response.json() : null).then(setContact).catch(() => {}); }, []);
  return <div className="story-page">
    <Navbar />
    <main>
      <section className="story-hero"><div><p className="eyebrow">OUR STORY</p><h1>Live with less.<br /><i>Love it longer.</i></h1><p className="story-lead">Verdant is a collection of thoughtful objects for a slower, more considered life.</p></div><div className="story-hero-image"><img src="https://images.unsplash.com/photo-1494438639946-1ebd1d20bf85?auto=format&fit=crop&w=1400&q=90" alt="Calm, light-filled home with considered objects" /></div></section>
      <section className="story-introduction"><p className="eyebrow">WHY VERDANT EXISTS</p><div><h2>Good design should make everyday life feel a little better.</h2><p>We started Verdant with a simple belief: the things we live with shape how we live. In a world of more, we look for the pieces that bring clarity, comfort, and quiet joy.</p><p>Every object in our collection is chosen for its material, function, and staying power. Nothing is here just to fill a shelf. These are useful, beautiful things made to become part of your everyday.</p></div></section>
      <section className="story-values"><div className="story-section-title"><p className="eyebrow">WHAT WE BELIEVE</p><h2>Considered by nature.</h2></div><div className="values-grid"><article><span>01</span><h3>Buy once, choose well.</h3><p>We favour timeless forms and dependable materials over passing trends. The best piece is the one you reach for again and again.</p></article><article><span>02</span><h3>Beauty belongs in the everyday.</h3><p>Practical does not have to mean ordinary. We seek out details that make daily rituals feel more intentional.</p></article><article><span>03</span><h3>Make room for better.</h3><p>We keep our collection focused and our standards high, so every addition has a reason to be here.</p></article></div></section>
      <section className="story-process"><div className="process-image"><img src="https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=85" alt="Design studio table with materials and sketches" /></div><div className="process-copy"><p className="eyebrow">OUR APPROACH</p><h2>From first sketch to daily ritual.</h2><div className="process-list"><div><strong>01</strong><p><b>We look closely.</b><br />We start with the details: how something feels in your hand, how it wears, and how it earns its place.</p></div><div><strong>02</strong><p><b>We choose carefully.</b><br />We work with makers and materials that reflect our values: honest, durable, and made with care.</p></div><div><strong>03</strong><p><b>We keep improving.</b><br />We listen, learn, and refine our collection so it serves real life beautifully.</p></div></div></div></section>
      <section className="story-impact"><p className="eyebrow">OUR COMMITMENT</p><h2>A lighter footprint, one choice at a time.</h2><p>We are building a more responsible way to shop by choosing long-lasting materials, reducing unnecessary packaging, and partnering with people who care about how things are made.</p><div className="impact-stats"><div><strong>100%</strong><span>Curated with intention</span></div><div><strong>0</strong><span>Trend-led throwaways</span></div><div><strong>1</strong><span>Longer-lasting standard</span></div></div></section>
      <section className="story-cta"><p className="eyebrow">MAKE SPACE FOR WHAT MATTERS</p><h2>Find something to live with.</h2><a className="button" href="/#shop">Explore the collection <span>→</span></a></section>
      <section className="story-contact"><div><p className="eyebrow">CONTACT</p><h2>{contact?.heading || "Come say hello."}</h2></div><div className="contact-details"><a href={`tel:${contact?.phone || "+919876543210"}`}>{contact?.phone || "+91 98765 43210"}</a><a href={`mailto:${contact?.email || "hello@verdantgoods.com"}`}>{contact?.email || "hello@verdantgoods.com"}</a><p>{contact?.address || "12 Garden Lane, Kolkata"}</p><p>{contact?.hours || "Mon-Sat, 10:00 AM-7:00 PM"}</p></div></section>
    </main>
    <footer><div><a className="logo" href="/">verdant<span>.</span></a><p>Objects for everyday living.</p><div className="social-links"><a href="https://www.facebook.com/" target="_blank" rel="noreferrer" aria-label="Facebook"><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14 8h3V4h-3c-3.3 0-5 1.9-5 5v3H6v4h3v4h4v-4h3l1-4h-4V9c0-.7.3-1 1-1Z" /></svg><span>Facebook</span></a><a href="https://www.instagram.com/" target="_blank" rel="noreferrer" aria-label="Instagram"><svg viewBox="0 0 24 24" aria-hidden="true"><rect x="3.5" y="3.5" width="17" height="17" rx="4" /><circle cx="12" cy="12" r="4" /><circle cx="17.5" cy="6.5" r=".8" className="social-dot" /></svg><span>Instagram</span></a></div></div><small>© 2026 Verdant Goods. Made with intention.</small></footer>
  </div>;
}
